"""Add unique constr token

Revision ID: 03b412e71519
Revises: 8dbb17d4938c
Create Date: 2024-10-28 00:15:21.702582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b412e71519'
down_revision: Union[str, None] = '8dbb17d4938c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('token_uc', 'user', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_uc', 'user', type_='unique')
    # ### end Alembic commands ###
